### ISSUE TITLE
Create New Items.otb

### ISSUE THREAD

**Issue by Codinablack** [giuinktse7/LapisItemEditor#5]
During startup, after selecting the assets folder we are given the option to select an items.otb or select "new items.otb", however, selecting "new items.otb" doesn't actually do anything, like at all. Screen stays the same, nothing happens. I waited and watched the application on my task manager to see if it was working in the background to make one, but it didn't show any cpu usage or changing memory usage either. It just doesn't do anything. 

The status reads "Ready" the entire time at the bottom of the screen and nothing happens.

**Comment by giuinktse7** [comment]
Thanks for reporting this! Fixed (hopefully) in the latest [release](https://github.com/giuinktse7/LapisItemEditor/releases/tag/v0.2.0-alpha).

I haven't tested it extensively though, feel free to create a new issue if it still doesn't work as expected.
