### ISSUE TITLE
Progress Bars

### ISSUE THREAD

**Issue by Codinablack** [giuinktse7/LapisItemEditor#6]
I would like to request an enhancement. We have the options to "Create Missing Items" and to "Update otb entries to match Tibia", however when using those options its rather hard to tell if anything has happened or not. 

It would be nice if once we clicked those buttons, we had a progress bar show up to show work being done, and also at the bottom where the status is always saying "loaded assets in x seconds" it would be nice to see a number of completed items like "67 Missing Items added" or something like that.

**Comment by giuinktse7** [comment]
Good points, I have tried to adress some of these in the latest [release](https://github.com/giuinktse7/LapisItemEditor/releases/tag/v0.2.0-alpha) that I just published. It's still far from perfect, but these changes should at least make it a bit easier to understand when/what is happening.

You can reply here if you are lacking feedback in more places and I'll see what I can do.

**Comment by Codinablack** [comment]
![image](https://github.com/giuinktse7/LapisItemEditor/assets/8696596/6400b4b0-2c92-417e-b5bb-0ff41948e03f)
![image](https://github.com/giuinktse7/LapisItemEditor/assets/8696596/e8b759b9-6b3d-45bf-b490-e208f2301033)
Looking great! That is awesome! Thank you! Fantastic tool!
